### PR TITLE
(maint) Update the puppet-agent package version inside Puppetfactory docker containers

### PR DESCRIPTION
**Pull request by greglarkin**

### CODE REVIEW

**Comment by greglarkin** [comment]
With the work to upgrade the classroom instances to use PE 2018.1.0 and the agent to 5.5.1, this change updates the agent inside the student Docker containers to 5.5.1 as well.

**Review by binford2k — APPROVED** [review]
I see no concerns with this, assuming that you acceptance test it :)

**Comment by greglarkin** [comment]
@binford2k There is a `rake beaker` task but no tests apparently. `rake spec` succeeded, but it's not clear what it tested, so I'll have a look. I ran the agent in the docker container manually, and it worked fine.

**Comment by greglarkin** [comment]
@binford2k Is that sufficient, and if so, what is the release process for this module?

**Comment by binford2k** [comment]
Since validating that this works and build a working agent container doesn't actually confirm whether it works in the classroom or LVM, this may require some manual validation. Build the module, drop on it on the LVM and do some representative testing. Drop it on a classroom VM and test the student compile masters in Architect. Use your own judgment about how much testing needs to be done -- some changes are bigger than others.

For future work, you may want to just parameterize the puppet agent version so you can declare it with the same version as installed on the master automatically.

**Pull request merged**
