### PR TITLE
Fixes fact when Docker not installed

### PR DESCRIPTION
**Pull request by petems**
- Also adds unit test for quick testing of docker_hosts fact

### CODE REVIEW

**Comment by binford2k** [comment]
The fact was already fixed. Kevin had used backticks instead of factor:;util::resolution.exec, which handles missing commands for you

**Comment by petems** [comment]
From my understanding, isn't the standard to to use the which check when a fact requires a certain path:

https://github.com/puppetlabs/puppetlabs-java/blob/master/lib/facter/java_version.rb#L25
https://github.com/puppetlabs/puppetlabs-git/blob/master/lib/facter/git_version.rb#L15

IIRC it requires less cycles than having to run the actual command. I might be wrong though...

**Comment by binford2k** [comment]
I don't know that there is such a standard. Even that java version fact isn't consistent. https://github.com/puppetlabs/puppetlabs-java/blob/master/lib/facter/java_version.rb#L48-L50

**Comment by petems** [comment]
That case is particular to OSX, because macs without Java installed still have a java executable shim that says "you need to install java" so the which check won't work because it will always be true, thats why there's unique logic there

**Pull request closed without merging**
